### ISSUE TITLE
Make filtering and lasso consistent in discovery

### ISSUE THREAD

**Issue by cabreraalex** [zeno-ml/zeno#356]
We should aim to make filtering as consistent as possible across the metadata widgets and lasso. 

- [ ] When you select a metadata column it should be represented in the embedding, maybe by opacity?
- [ ] And when you clear all, the lasso selection should go away.
- [ ] When you re-run projection, it should also clear the lasso selection.
- [ ] Maybe when you reproject we put those filters somewhere else? I cleared it by accident a couple of times and it reset to the main filter when I just wanted it to filter to the projection

**Comment by xnought** [comment]
@cabreraalex when you say lasso selection, do you mean the points highlighted in the scatter or do you mean the ids stored as the lasso selection in the chip?

**Comment by cabreraalex** [comment]
Hmm unsure! Maybe both? In general I think we should think a bit about how the different filters and projections should interact.
