### ISSUE TITLE
typescript Interface or docs for viewFunction

### ISSUE THREAD

**Issue by xnought** [zeno-ml/zeno#453]
**A typescript interface for the viewFunction.**

A interface would help me know what the function does, if it returns something, and if it changes the memory of any of the parameters. 

I think it populates the div with the right stuff that was given as an argument. (could be wrong)

<img width="452" alt="Screenshot 2022-12-16 at 12 22 29 AM" src="https://user-images.githubusercontent.com/65095341/208055068-8405b63e-f8e9-473f-b9d5-8c6a61058b4d.png">

(for example in `ListView.svelte`)

**Comment by xnought** [comment]
aha I see, it has this signature https://github.com/zeno-ml/instance-views/blob/main/image-classification/index.mjs#L828
<img width="350" alt="Screenshot 2022-12-16 at 1 00 30 AM" src="https://user-images.githubusercontent.com/65095341/208061954-72945224-1e39-4fbf-acbb-21b55ed584fc.png">

**Comment by cabreraalex** [comment]
Thanks a ton for this, very helpful
