### ISSUE TITLE
add instance tags and similar instance search

### ISSUE THREAD

**Issue by cabreraalex** [zeno-ml/zeno#499]
In addition to formal slices, it would be nice to have "tags" which are arbitrary groups of instances.

It would be great to also have "similar instance search" for tags to find additional instances using the embeddings. We can use something like [FAISS](https://github.com/facebookresearch/faiss) for this

**Comment by xnought** [comment]
You might also want to see the comparisons/benchmarks vs. other [nearest neighbor implementations here](http://ann-benchmarks.com/). Also [Spotify Annoy](https://github.com/spotify/annoy) looks promising too.
