### ISSUE TITLE
if we optimize based on my slice, how much would my model improve?

### ISSUE THREAD

**Issue by xnought** [zeno-ml/zeno#518]
Ask yourself: What if I did optimize my model on this slice? What would happen? Could I estimate how the total performance or performance on other slices would decline?

![Screenshot 2023-01-27 at 10 12 03 PM](https://user-images.githubusercontent.com/65095341/215291853-39af851c-99ce-46f1-9068-209b645f461a.png) circled in red

from the paper -> https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9906903

In the report the slices could be ranked by potentially most helpful.

idk these are half baked thoughts. But its like prediction of what the report would look like in the future: What could I expect the next report if I do optimize on these slices?

**Comment by cabreraalex** [comment]
Super cool idea!
