### ISSUE TITLE
lru_cache memory leaks when applied to class functions

### ISSUE THREAD

**Issue by xnought** [zeno-ml/zeno#522]
https://stackoverflow.com/questions/33672412/python-functools-lru-cache-with-instance-methods-release-object

**Comment by xnought** [comment]
Didn't see problems with Zeno, but could become a problem in the future

**Comment by xnought** [comment]
Issue seems to be that lru_cache also hashes the self parameter

**Comment by cabreraalex** [comment]
Should we move that function outside of the Zeno object?

**Comment by xnought** [comment]
That would work, switching to `methodtool.lru_cache` will work in the future.
