### ISSUE TITLE
Simplify the add slice button

### ISSUE THREAD

**Issue by erica-w-fu** [zeno-ml/zeno#573]
Currently when you add a slice, a complex view of many dropdowns appears. This is very overwhelming to the user and also unnecessary for most slicing cases.
![image](https://user-images.githubusercontent.com/72369224/217918766-d4083882-8850-4565-b23d-b225f1e93bff.png)

Instead, a popup of dropdowns, when a user clicks the plus button, only a popup for the name of the slice should appear.
![image](https://user-images.githubusercontent.com/72369224/217920607-cc565659-77eb-409d-9c2c-8c5b3498421e.png)![image](https://user-images.githubusercontent.com/72369224/217920539-403ba9a4-e589-426d-ad39-bd6f1ec7e879.png)

The complex slice dropdown view can still be accessed by editing the slice.

**Comment by cabreraalex** [comment]
I think with the simpler slice creation UI we can keep it as is.
