### ISSUE TITLE
[demo request] Adding three demos

### ISSUE THREAD

**Issue by LangDaoAI** [zeno-ml/zeno#603]
Hi, team,

request adding three demos:

1 NLP: entity extraction
2 CV: image segmentation
3 CV: object detection

Thanks!

**Comment by cabreraalex** [comment]
Hi @LangDaoAI! 

We currently have a binary segmentation model example in `examples/segmentation`. Do you need a multiclass segmentation example?

For entity extraction and object detection do you have specific output format examples you could share? We will have to build new views for those.

Thanks!!
