### ISSUE TITLE
[demo request] text transformers

### ISSUE THREAD

**Issue by xnought** [zeno-ml/zeno#611]
~https://github.com/karpathy/minGPT or https://github.com/karpathy/nanoGPT~

Use huggingface transformers library to compare some text transformers across the same data.

- what dataset to run on? How many next word predictions to run?
- what instance view javascript component would be necessary?

**Comment by xnought** [comment]
This would also be a cool example to have up with @inference

**Comment by xnought** [comment]
Also could be a good test for a large dataset

**Comment by cabreraalex** [comment]
I'm going to work on a text generation view this week we could use. Simple just showing the "prompt" and the output.

**Comment by xnought** [comment]
Or use https://huggingface.co/docs/transformers/model_doc/gpt2

**Comment by xnought** [comment]
I'm still getting BS text generation results ahh

**Comment by xnought** [comment]
Okay these text transformers are overhyped in the media in terms of performance.
