### ISSUE TITLE
examples documentation

### ISSUE THREAD

**Issue by xnought** [zeno-ml/zeno#630]
We should probably have a readme for each separate example explaining how to download data, download other dependencies (maybe view a requirements.txt we also add), and what this example illustrates (maybe some video or screenshots).

**Comment by xnought** [comment]
Also what If I want to git clone just one example? Is there some git magic to only get those files?

**Comment by xnought** [comment]
Or maybe you can easily download example with the zeno command

**Comment by xnought** [comment]
Also the data folder should be kept inside each example so people can easily download just the examples and know where to put the data

**Comment by cabreraalex** [comment]
100% I want to redo how the examples are structured. Maybe we create a separate repository for all examples? I haven't decided what the best way to organize them are

**Comment by xnought** [comment]
Hmm good question. The one big upside of having the examples here is that its easier for development.

**Comment by xnought** [comment]
Perhaps if we can have the examples in a separate repo and do a repository link thingy

**Comment by cabreraalex** [comment]
Made it into a new repo you can clone into the main Zeno folder to still do debugging.

**Comment by xnought** [comment]
Note in the future it might be nice to make it a submodule https://github.blog/2016-02-01-working-with-submodules/. Too much work for now.
