### ISSUE TITLE
Not able to use pytorch lightning models using custom transforms 

### ISSUE THREAD

**Issue by debalabbas** [zeno-ml/zeno#646]
I trained a pytorch lighting model using Custom transform.
```
from models.lightning_models import ResNet50Similarity, SquarePad
import torchvision.transforms.functional as F


transforms = torchvision.transforms.Compose(
        [   SquarePad(),
            torchvision.transforms.Resize((224, 224)),
            torchvision.transforms.ToTensor(),
            # Means and STDev from ResNet model
            torchvision.transforms.Normalize( mean = (0.485, 0.456, 0.406), std = (0.229, 0.224, 0.225)),
        ]
    )

@model
def load_model(model_path):
    model = torch.load(model_path).to('cuda')
    classes = list(model.classes.keys())


```
Now when I try to load the model in zenoml it does not work , I get the error message
```
Can't get attribute 'SquarePad' on <module '__main__'>
```
Do I need to declare it in the `__init__` function or someplace else to make it available to the runner

**Comment by cabreraalex** [comment]
Hi, thanks for trying it out! Could you share which line that error happens? And your config file/how you are running Zeno?

**Comment by debalabbas** [comment]
So I get the error from `zeno/processing`, when it tries to load the model
Specifically this line `model = torch.load(model_path).to('cuda')`. 
I am running zeno using shell, and have built it on top of CIFAR example.

This is how my `toml` file looks
```
functions = "./"
view = "image-classification"
metadata = "flywheel_data.csv"
models = [
    "../../../artifacts/model_exports/ResNet50-LinearTrained.pt"
]
data_path = " ../../../../../data/datasets/images/test_data"
data_column = "id"
id_column = "id"
label_column = "component"
batch_size = 512
samples = 32
port = 3000
host = "0.0.0.0"
```

**Comment by cabreraalex** [comment]
Hmm one potential issue is the `model_path` used in that function is relative to where you run the command, not where the TOML file is (easiest is to run zeno from where the TOML file is). You can try to print out the path or check it exists with `os`.

Defining the transform where you have it should be fine, that's how I have it set up for various examples as well. 

Maybe you didn't share the full code, but `@model` should be returning another function that takes in a dataframe and ZenoOptions, you mentioned you're following the CIFAR example but here is a similar block of code: https://github.com/zeno-ml/example-images/blob/main/tests/loading.py
