### ISSUE TITLE
consider renaming @inference to @playground

### ISSUE THREAD

**Issue by xnought** [zeno-ml/zeno#654]
My dumbo brain keeps interpreting the inference decorator as the model decorator. I think it's because I associate inference with making a ton of predictions. 

In a way, the gradio interface is more like a model playground area. People can play around with the model here. Why not name the decorator `playground` instead?

Or perhaps this is a non-issue. I don't have a strong opinion here.

**Comment by xnought** [comment]
@cabreraalex thoughts?

**Comment by cabreraalex** [comment]
100% I hate the name now. idk about playground though

**Comment by xnought** [comment]
hmmm hopefully the name arises for what it actually is. 

### What do you do with it?
Can build interfaces with gradio components and your model.

### What makes it unique compared to the other Zeno tabs?
Can see live model output with your own data. For example, text classification, you can drag and drop an image to see a model classify the result. 

With Zeno, you have to define data with the config. Adding more data to test a few instances is not necessarily the easiest.

**Comment by cabreraalex** [comment]
actually playground is growing on me

**Comment by cabreraalex** [comment]
honestly @model should be @inference

**Comment by xnought** [comment]
Actually true that. 

Only caveat: I'm trying to think are there models that don't infer stuff? Do generative models use that inference verbage?
