### ISSUE TITLE
Allowing to see the same model with different prompt or different parameters

### ISSUE THREAD

**Issue by Rami-Ismael** [zeno-ml/zeno#709]
I am working in a team.  They would see the difference in the text generated from different prompts.

**Comment by cabreraalex** [comment]
Hi Rami! Thanks for reaching out! We have a "comparison" tab on the top right where you can pick two different models and compare the prompts side-by-side. I'm happy to set up a meeting with ya'll to help set that up as well

**Comment by Rami-Ismael** [comment]
I am interested what time are you free to meet?

**Comment by cabreraalex** [comment]
Please email me at cabrera@cmu.edu and we can set something up this week!
