### ISSUE TITLE
Install fails with Python 3.11

### ISSUE THREAD

**Issue by willeppy** [zeno-ml/zeno#765]
Installing python package doesnt work in clean environment with python 3.11 because of issue with pyarrow.

I'm not super familiar with how poetry works but I didnt see pyarrow as explicit dependency, so might be worth limiting to less than python 3.11 for now or forcing newer versions of pyarrow

To repro
```bash
conda create -n zenotest python
conda activate zenotest
pip install zenoml
```

Fails with weird issue for pyarrow:
```bash
Failed to build pyarrow
ERROR: Could not build wheels for pyarrow, which is required to install pyproject.toml-based projects
```

However if environment is created with python 3.10 explicitly then works fine
```bash
conda create -n zenotest python=3.10
conda activate zenotest
pip install zenoml
```

**Comment by cabreraalex** [comment]
Apparently had it set to not support 3.11 so it was installing an old version that required pyarrow that did not work for 3.11. Anyway thanks for the find, should be fixed now.
