### ISSUE TITLE
Consider making "size" in chart dropdown a standalone top-level option

### ISSUE THREAD

**Issue by cabreraalex** [zeno-ml/zeno#830]
It might be confusing that size is part of the "metrics" dropdown in charts. Consider making it another top-level option.

Could also just rename it to "slice size"

**Comment by stevenyh3** [comment]
Yeah, that's a good idea. It also makes more sense if we want to support charts with no models or metrics, such as size-based charts. Will think bout it.

**Comment by cabreraalex** [comment]
For now just rename to "slice size" from "size"
