### ISSUE TITLE
Comparative slice finder: disallow non-numeric values as target metrics

### ISSUE THREAD

**Issue by neubig** [zeno-ml/zeno#871]
I got this confusing result from the comparative slice finder:

![Screen Shot 2023-06-21 at 5 53 57 PM](https://github.com/zeno-ml/zeno/assets/398875/56fdcca3-303a-4bbc-819b-96fe6a638f59)

This was due to human error where I selected "output" as the target metric, which doesn't make any sense because "output" is a string. It’s not shown in the non-comparative slice finder for some reason, so I don’t know where the consistency comes from.

It would be good to not allow non-numeric values as the "target metric" in the comparative slice finder to prevent this kind of error.

**Comment by cabreraalex** [comment]
We calculate difference in the comparison view for non-numeric columns as a 1 or 0 same or different. So you can actually use it as a metric column and find slices where the models disagree the most for a given column.

Maybe we can change the name or tooltip to clarify this? Or does that make sense?

**Comment by neubig** [comment]
Ah, that's an interesting idea! But yeah, changing the name and tooltip would make sense. The tooltip right now specifically says the function is continuous :)

<img width="482" alt="Screen Shot 2023-06-23 at 8 58 02 AM" src="https://github.com/zeno-ml/zeno/assets/398875/3a234b55-b136-4ee2-9ffe-c257274bd184">
