### ISSUE TITLE
Instance Exploration: Shift-drag of slices to folders doesn't work

### ISSUE THREAD

**Issue by neubig** [zeno-ml/zeno#875]
It'd be nice if we could shift-click slices to select many of them, and then simultaneously drag them all to a folder. However, this currently doesn't work; only the first slice moves to the folder. See attached video.

https://github.com/zeno-ml/zeno/assets/398875/08aa4b97-d742-4032-807f-8b63f51554ea

**Comment by cabreraalex** [comment]
Glad you noticed the shift-clicking :)
