### ISSUE TITLE
Make chatbot view more concise for very long conversations

### ISSUE THREAD

**Issue by neubig** [zeno-ml/zeno#905]
Currently for very long conversations, the chatbot display can be extremely long and take up too much screen space.

It might be nice if only the final N utterances were shown by default (e.g. N=6 or so), but then the full context could be expanded with a button click or something.

**Comment by Sparkier** [comment]
This is probably one for https://github.com/zeno-ml/instance-views. I copied your issue over as https://github.com/zeno-ml/instance-views/issues/5
